---
- name: Ara label playbook
  hosts: localhost
  tasks:
    - name: Add a static label to this playbook (the one that is running)
      run_once: true
      ara_label:
        state: present
        labels:
          - state:running

    - name: Add a static label to this playbook (the one that is running)
      # Note: By default Ansible will run this task on every host.
      # Consider the use case and declare 'run_once: true' when there is no need to
      # run this task more than once.
      # This might sound obvious but it avoids updating the same labels 100 times
      # if there are 100 hosts, incurring a performance penalty needlessly.
      run_once: true
      ara_label:
        state: present
        labels:
          - state:running

    - name: Add dynamically templated labels to this playbook
      ara_label:
        state: present
        labels:
          - "git:{{ lookup('pipe', 'git -C ' ~ playbook_dir ~ ' rev-parse HEAD') }}"
          - "os:{{ ansible_distribution }}-{{ ansible_distribution_version }}"

    - name: Add labels to a specific playbook
      ara_label:
        state: present
        playbook_id: 1
        labels:
          - state:deployed

    - name: Remove labels from the running playbook (if they exist)
      ara_label:
        state: absent
        labels:
          - state:running