---
# Wait loop example - check repeatedly until done using native async_status with retries
# This demonstrates using Ansible's built-in retry mechanism to poll for completion

- name: Wait for job completion with retry loop
  hosts: localhost
  gather_facts: true
  vars:
    job_name: "wait_loop_task"
  tasks:
    - name: Load or start task
      block:
        - name: Try load
          ansible.builtin.include_role:
            name: rstyczynski.ansible.async_job_load
          vars:
            async_job_load_playbook_name: "scenario_03_wait_loop"
            async_job_load_job_name: "{{ job_name }}"

        - name: Start if not found
          ansible.builtin.shell: "for i in {1..12}; do echo \"Progress: iteration $i at $(date)\"; sleep 5; done; echo 'Done'"
          async: 90
          poll: 0
          register: new_job
          when: not async_job_load_found

        - name: Save if started
          ansible.builtin.include_role:
            name: rstyczynski.ansible.async_job_save
          vars:
            async_job_save_playbook_name: "scenario_03_wait_loop"
            async_job_save_job_name: "{{ job_name }}"
            async_job_save_ansible_job_id: "{{ new_job.ansible_job_id }}"
            async_job_save_host: "{{ inventory_hostname }}"
          when: not async_job_load_found

    - name: Wait for completion with native async_status
      ansible.builtin.async_status:
        jid: "{{ async_job_load_ansible_job_id if async_job_load_found else new_job.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 15
      delay: 2
      ignore_errors: true
      changed_when: false  # Checking status is a read operation

    - name: Display job status
      ansible.builtin.debug:
        msg: |
          Job: {{ job_name }}
          Status: {{ 'COMPLETED' if result.finished | default(false) else 'RUNNING' }}
          {% if result.finished | default(false) %}
          Return Code: {{ result.rc | default('N/A') }}
          {% endif %}
          {% if result.failed | default(false) %}
          Error: {{ result.msg | default('Unknown error') }}
          {% endif %}

    - name: Display stdout output
      ansible.builtin.debug:
        msg: "{{ result.stdout_lines if (result.stdout is defined and result.stdout | length > 0) else ['(no output)'] }}"

    - name: Display stderr output
      ansible.builtin.debug:
        msg: "{{ result.stderr_lines if (result.stderr is defined and result.stderr | length > 0) else ['(no errors)'] }}"
