---
- name: Test OCI backend - Save new job
  hosts: localhost
  gather_facts: yes
  vars:
    oci_bucket: "{{ lookup('env', 'OCI_BUCKET') }}"
    test_job_name: "oci_test_fresh_{{ ansible_date_time.epoch }}"

  tasks:
    - name: Get OCI namespace
      ansible.builtin.command: oci os ns get --query data --raw-output
      register: oci_ns_result
      changed_when: false

    - name: Set OCI namespace
      ansible.builtin.set_fact:
        oci_namespace: "{{ oci_ns_result.stdout }}"

    - name: Display test info
      ansible.builtin.debug:
        msg:
          - "Testing OCI save with fresh job"
          - "Job name: {{ test_job_name }}"
          - "Bucket: {{ oci_bucket }}"

    - name: Start async task
      ansible.builtin.command: sleep 10
      async: 30
      poll: 0
      register: async_result

    - name: Save to OCI
      ansible.builtin.include_role:
        name: rstyczynski.ansible.async_job_save
      vars:
        async_job_save_backend: "oci"
        async_job_save_job_name: "{{ test_job_name }}"
        async_job_save_ansible_job_id: "{{ async_result.ansible_job_id }}"
        async_job_save_host: "{{ inventory_hostname }}"
        async_job_save_oci_bucket: "{{ oci_bucket }}"
        async_job_save_oci_namespace: "{{ oci_namespace }}"
        async_job_save_metadata:
          test: "save_test"

    - name: Display save result
      ansible.builtin.debug:
        msg: "✓ Saved to: {{ async_job_save_state_file }}"

    - name: Load from OCI
      ansible.builtin.include_role:
        name: rstyczynski.ansible.async_job_load
      vars:
        async_job_load_backend: "oci"
        async_job_load_job_name: "{{ test_job_name }}"
        async_job_load_oci_bucket: "{{ oci_bucket }}"
        async_job_load_oci_namespace: "{{ oci_namespace }}"

    - name: Verify load result
      ansible.builtin.debug:
        msg:
          - "✓ Found: {{ async_job_load_found }}"
          - "✓ Job ID: {{ async_job_load_ansible_job_id }}"
          - "✓ Metadata: {{ async_job_load_metadata }}"

    - name: Check status
      ansible.builtin.async_status:
        jid: "{{ async_job_load_ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 5
      delay: 3

    - name: Final result
      ansible.builtin.debug:
        msg: "✓✓✓ OCI BACKEND FULLY TESTED - SAVE AND LOAD WORKING ✓✓✓"
