---
- name: Test secret with lookup
  hosts: localhost
  tasks:
    - name: Access secret via lookup
      ansible.builtin.debug:
        msg: "Secret value is: {{ lookup('env', 'MY_SECRET') }}"

    - name: Check secret length
      ansible.builtin.debug:
        msg: "Secret length is: {{ lookup('env', 'MY_SECRET') | length }}"
