---
- name: "Auth: Check for GitHub token in environment"
  ansible.builtin.set_fact:
    github_token: "{{ lookup('env', 'GH_TOKEN') | default(lookup('env', 'GITHUB_TOKEN'), true) }}"

- name: "Auth: Check if .netrc file exists"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.netrc"
  register: netrc_file
  when: github_token == ""

- name: "Auth: Read .netrc file for github.com credentials"  # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      awk '
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        /^[[:space:]]*machine[[:space:]]+github\.com/ { in_github=1; next }
        in_github && /^[[:space:]]*machine[[:space:]]/ { in_github=0 }
        in_github && /^[[:space:]]*password[[:space:]]/ { print $2; exit }
      ' ~/.netrc
  args:
    executable: /bin/bash
  register: netrc_token
  changed_when: false
  failed_when: false
  when:
    - github_token == ""
    - netrc_file.stat.exists | default(false)

- name: "Auth: Set token from .netrc if found"
  ansible.builtin.set_fact:
    github_token: "{{ netrc_token.stdout }}"
  when:
    - github_token == ""
    - netrc_token.stdout is defined
    - netrc_token.stdout != ""
  no_log: true

- name: "Auth: Display token source"
  ansible.builtin.debug:
    msg: "GitHub token found in environment variables"
  when: github_token != "" and (netrc_token.stdout is not defined or netrc_token.stdout == "")

- name: "Auth: Display token from netrc"
  ansible.builtin.debug:
    msg: "GitHub token found in ~/.netrc for github.com"
  when: github_token != "" and netrc_token.stdout is defined and netrc_token.stdout != ""

- name: "Auth: Warning if no token found"
  ansible.builtin.debug:
    msg: "WARNING: No GitHub token found in GH_TOKEN, GITHUB_TOKEN environment variables, or ~/.netrc"
  when: github_token == ""

- name: "Auth: Authenticate gh CLI with token"  # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: set -o pipefail && echo "{{ github_token }}" | gh auth login --with-token
  args:
    executable: /bin/bash
  when:
    - gh_version.rc == 0
    - github_token != ""
    - gh_auth_status.rc != 0
  register: gh_auth_result
  changed_when: gh_auth_result.rc == 0
  no_log: false

- name: "Auth: Verify authentication after login"  # noqa: command-instead-of-module
  ansible.builtin.command: gh auth status
  register: gh_auth_verify
  changed_when: false
  failed_when: false
  when: gh_auth_result is not skipped and gh_auth_result.rc is defined

- name: "Auth: Display authentication success"
  ansible.builtin.debug:
    msg: "Successfully authenticated with GitHub CLI using token"
  when: gh_auth_verify is not skipped and gh_auth_verify.rc == 0
