---
- name: "PR Status: Fail if gh CLI is not installed"

  ansible.builtin.fail:
    msg: "GitHub CLI (gh) is not installed. Please install it first: https://cli.github.com/"
  when: gh_version.rc != 0

- name: "PR Status: Fail if gh CLI is not authenticated"

  ansible.builtin.fail:
    msg: "GitHub CLI is not authenticated. Please run: gh auth login"
  when: gh_version.rc == 0 and gh_auth_status.rc != 0

- name: "PR Status: Get current branch name"  # noqa: command-instead-of-module

  ansible.builtin.command:
    cmd: git branch --show-current
    chdir: "{{ dest_path }}"
  register: current_branch
  changed_when: false

- name: "PR Status: Get PR number for current branch"  # noqa: command-instead-of-module

  ansible.builtin.command:
    cmd: gh pr list --head {{ current_branch.stdout }} --json number --jq '.[0].number'
    chdir: "{{ dest_path }}"
  register: pr_number
  changed_when: false
  failed_when: false

- name: "PR Status: Fail if no PR exists for current branch"

  ansible.builtin.fail:
    msg: "No pull request found for branch {{ current_branch.stdout }}"
  when: pr_number.stdout == ""

- name: "PR Status: Get PR status checks"  # noqa: command-instead-of-module

  ansible.builtin.command:
    cmd: gh pr view {{ pr_number.stdout }} --json statusCheckRollup --jq '.statusCheckRollup'
    chdir: "{{ dest_path }}"
  register: pr_status_checks
  changed_when: false
  failed_when: false

- name: "PR Status: Parse status checks"

  ansible.builtin.set_fact:
    status_checks: "{{ pr_status_checks.stdout | from_json }}"
  when: pr_status_checks.stdout != "" and pr_status_checks.stdout != "null"

- name: "PR Status: Display status when no checks exist"

  ansible.builtin.debug:
    msg: "No status checks configured for this PR"
  when: pr_status_checks.stdout == "" or pr_status_checks.stdout == "null" or pr_status_checks.stdout == "[]"

- name: "PR Status: Count status checks"

  ansible.builtin.set_fact:
    total_checks: "{{ status_checks | length }}"
    failed_checks: "{{ status_checks | selectattr('status', 'equalto', 'COMPLETED') | rejectattr('conclusion', 'in', ['SUCCESS', 'NEUTRAL', 'SKIPPED']) | list }}"
    pending_checks: "{{ status_checks | rejectattr('status', 'equalto', 'COMPLETED') | list }}"
    passed_checks: "{{ status_checks | selectattr('status', 'equalto', 'COMPLETED') | selectattr('conclusion', 'in', ['SUCCESS', 'NEUTRAL', 'SKIPPED']) | list }}"
  when: status_checks is defined and status_checks | length > 0

- name: "PR Status: Display status check summary"

  ansible.builtin.debug:
    msg:
      - "Total status checks: {{ total_checks }}"
      - "Passed checks: {{ passed_checks | length }}"
      - "Failed checks: {{ failed_checks | length }}"
      - "Pending checks: {{ pending_checks | length }}"
  when: status_checks is defined and status_checks | length > 0

- name: "PR Status: Display failed checks"

  ansible.builtin.debug:
    msg: "Failed check: {{ item.name }} - {{ item.conclusion }}"
  loop: "{{ failed_checks }}"
  when:
    - status_checks is defined
    - failed_checks is defined
    - failed_checks | length > 0

- name: "PR Status: Display pending checks"

  ansible.builtin.debug:
    msg: "Pending check: {{ item.name }}"
  loop: "{{ pending_checks }}"
  when:
    - status_checks is defined
    - pending_checks is defined
    - pending_checks | length > 0

- name: "PR Status: Display pending checks info"

  ansible.builtin.debug:
    msg: "{{ pending_checks | length }} status check(s) still pending/in progress"
  when:
    - status_checks is defined
    - pending_checks is defined
    - pending_checks | length > 0

- name: "PR Status: Set fact for pending checks"

  ansible.builtin.set_fact:
    has_pending_checks: true
  when:
    - status_checks is defined
    - pending_checks is defined
    - pending_checks | length > 0

- name: "PR Status: Set fact for no pending checks"

  ansible.builtin.set_fact:
    has_pending_checks: false
  when:
    - status_checks is defined
    - pending_checks is defined
    - pending_checks | length == 0

- name: "PR Status: Fail if any status checks failed"

  ansible.builtin.fail:
    msg: "{{ failed_checks | length }} status check(s) failed"
  when:
    - status_checks is defined
    - failed_checks is defined
    - failed_checks | length > 0

- name: "PR Status: Display success message"

  ansible.builtin.debug:
    msg: "All status checks passed! ({{ passed_checks | length }} checks completed successfully)"
  when:
    - status_checks is defined
    - status_checks | length > 0
    - failed_checks is defined
    - pending_checks is defined
    - passed_checks is defined
    - failed_checks | length == 0
    - pending_checks | length == 0
    - passed_checks | length > 0
