---
- name: "{{ calc_title }}"
  ansible.builtin.command:
    cmd: python3 -c "print({{ calc_equation }})"
  register: calc_result
  changed_when: false

- name: "{{ calc_title }} - result"
  ansible.builtin.debug:
    msg: "{{ calc_equation }} = {{ calc_result.stdout }}"
